### ISSUE TITLE
Vimeo Pro Settings blank

### ISSUE THREAD

**Issue by psntr** [ttillberg/acf-vimeo-pro-data#18]
Hi @ttillberg!

Again thank you for this amazing work. 

I updated your plugin (1.1.3) then my WordPress (5.1) and ACF (5.7.12). After that I notice that my Vimeo Pro Settings under the Settings menu was "blank".

<img width="959" alt="screen shot 34" src="https://user-images.githubusercontent.com/20617539/53815693-66780f80-3f62-11e9-91c4-9333b7de2b97.png">

I check my console, no error was shown. Nevertheless, the plugin still works. Any idea where this might come from?

Cheers.

**Comment by ttillberg** [comment]
Hello! Do you have the ability to fetch or refresh new videos? Also which version of ACF are you using? Thanks for your feedback!

**Comment by psntr** [comment]
@ttillberg thanks for your reply. 

To answer your questions:
**Do you have the ability to fetch or refresh new videos?**
Yes

**Also which version of ACF are you using?** 
ACF Pro Version 5.7.12

Here is what I see when inspecting the settings menu. 
<img width="1213" alt="screen shot 30" src="https://user-images.githubusercontent.com/20617539/53831914-3e9aa300-3f86-11e9-8781-71045a49347e.png">

Also my Vimeo token is wrapped inside a script tag:
<script type="text/javascript">
/* <![CDATA[ */
var server_vars = {"vimeo_token":"_myToken_"};
/* ]]> */
</script>

**Comment by ttillberg** [comment]
@psntr thanks for the debugging info - I think it's fixed now (1.1.5), however now I'm having trouble to update the plugin through Github Updater, I've only been trying on one instance for now...

**Comment by psntr** [comment]
@ttillberg Thank you for the really quick fix. About the Github Updater, sorry I wasn't able to use it. Since the very beginning, the Github Updater kept on returning an error so I couldn't use it.

**Comment by ttillberg** [comment]
@psntr All good!

**Comment by psntr** [comment]
@ttillberg Thank you so much!

**Comment by psntr** [comment]
I spoke a bit too fast, with the lastest version although the original issu is fixed, now the output (frontend) seems not to work anymore. Is is the same on your side?

**Comment by ttillberg** [comment]
Oh sorry! It's working fine for me. How do you use the data? Via PHP or JSON-API ? (or other...)

**Comment by psntr** [comment]
No worries, I should have double checked.
That's my method:
```php
<?php

// Vimeo ACF
 $video_vimeo = get_field('video_vimeo', $last_id);

// Vimeo metadata

$array_vimeo = json_decode(json_encode($video_vimeo), true);
?>
```

**Comment by ttillberg** [comment]
Thanks. Do you get an error or just emptiness ?

**Comment by ttillberg** [comment]
Could you try just doing a `var_dump` / `print_r( $video_vimeo)` without the decode part

**Comment by psntr** [comment]
It gave me error, it seems like the $video_vimeo is not existent, therefore returning me an error when trying to get anything related to the $array_vimeo

**Comment by psntr** [comment]
Our comment came across, so it doesn't give me error when i `var_dump` or `print_r` the $video_vimeo. It just doesn't return anything.

**Comment by ttillberg** [comment]
Hi @psntr ! I tested the new version here and it seems to be working just fine, which doesn't really help for the debugging. 

First, can you still refresh, load a new video, save without any problem? 

Second, one hint for me is your usage of `json_encode` `json_decode` which seems a bit redundant but there might be a reason for you to do so (database encoding, PHP version,... ). 
There's one line of code that changed in the latest update which refers to this [here](https://github.com/ttillberg/acf-vimeo-pro-data/commit/d7a34654849456be11b854831007e7e9b0defa1e#diff-66f28592a41790ed4941e42cfc28a5e5R421) and I wonder if it could be the problem. Would you mind going in and trying out adding an extra `json_encode / true` or removing the decoding all together ?

`line 421 of wp-content/plugins/acf-vimeo-pro-data/fields/acf-vimeo_pro_data-v5.php`

**Comment by psntr** [comment]
@ttillberg Hi sorry for the late reply.

I've tried with a local version, it worked once I "re-updated" the post. Didn't need to change the `json_encode` nor `json_decode`. Strangely the same manipulations didn't work on the live version. I will need to make further tests. I keep you on the loop.

**Comment by ttillberg** [comment]
Thanks for checking. Let me know if you find something. If you could give me access I'm happy to help out too.

**Comment by psntr** [comment]
@ttillberg it's finally solved, sorry for going replying earlier, been pretty busy. So to summarize, for I don't know what reason, we needed to update all links again after updating the plugin. 
But now it's working like before with the newest version. 

Thank you for much for you considerable time!

**Comment by psntr** [comment]
@ttillberg Hi again, after my message on 21 March, we haven't uploaded any videos, but recently we added a video on Vimeo that contains special characters like double quote. For instance:

Artist name, "my title", 2019

When title of the video are like that, nothing shows up with:

`<?php
// Vimeo ACF
 $video_vimeo = get_field('video_vimeo', $last_id);
var_dump($video_vimeo);
?>`

In the backend, everything seems fine.

**Comment by psntr** [comment]
I did another quick test, if your video description also contains that character, it's not fetching properly on the front-end.
