### ISSUE TITLE
UI adjustments PR proposal 

### ISSUE THREAD

**Issue by hatsumatsu** [ttillberg/acf-vimeo-pro-data#21]
Hi and thanks for this really cool plugin, I was so close to writing something from scratch until I found yours. I just made some UI adjustments to bring the style closer to the WP core UI, let me know if you're interested in a PR.

<img width="872" alt="Screenshot 2019-04-16 at 11 51 56" src="https://user-images.githubusercontent.com/3452400/56200645-76920d00-603f-11e9-9d41-e496217396ac.png">
<img width="713" alt="Screenshot 2019-04-16 at 11 59 24" src="https://user-images.githubusercontent.com/3452400/56200652-7a259400-603f-11e9-8fdc-2ffa943a7d56.png">

**Comment by ttillberg** [comment]
@hatsumatsu That's pretty neat. Would love to try that out, would you mind PR against the dev branch ?

**Comment by ttillberg** [comment]
@hatsumatsu 🙏thanks so much for this and so sorry for not having been responsive enough ! I merged the PR a little while ago.
