### ISSUE TITLE
Vimeo PLUS Support

### ISSUE THREAD

**Issue by mihazs** [ttillberg/acf-vimeo-pro-data#23]
It's possible to add support to Vimeo Plus?

**Comment by ttillberg** [comment]
As far as I know you need  Vimeo PRO to request and use the video files independently. So it's not a choice from our side really.

**Comment by mihazs** [comment]
Ok, but, it's possible only to get the url of the video? The feature of list all videos of my account it's awesome. It's possible to choose the video and get the url or video ID?
