### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by intelligence** [ttillberg/acf-vimeo-pro-data#25]
First and foremost, thanks for an awesome field addon for ACF, been contemplating doing something similar for ages! :pray:

I went ahead and added this repo to packagist so it's possible to install easily via composer. However, it prompted me to enable the service hook so that the package is up to date. Would you be able to set it up?

Some information here: https://packagist.org/about#how-to-update-packages

Thanks again!

**Comment by ttillberg** [comment]
Thanks! I just tried to submit from my end but I can't since the plugin/namespace is already registered. 

> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at ttillberg

I don't know if it's possible to delete and start over ? Otherwise, to set up the service hook manually I'd need _your_ API TOKEN which would be odd OR I could add you as maintainer.

**Comment by intelligence** [comment]
I deleted it from my profile just now, so you should be able to set it up from scratch with your account :)

**Comment by ttillberg** [comment]
Great, had to add a license too but should be all hooked up now. Thanks for the heads up.
Just curious, how do you use `composer` with WP dev ?

**Comment by intelligence** [comment]
Awesome!

I'm using the [Roots stack](https://roots.io) which comes preconfigured for using composer. If you don't want to use the full stack, look into using just [Bedrock](https://roots.io/bedrock/).
