### ISSUE TITLE
Notice: Undefined index: font_size

### ISSUE THREAD

**Issue by intelligence** [ttillberg/acf-vimeo-pro-data#26]
Plugin spits out a notice about undefined index for font_size

<img width="700" alt="Skärmavbild 2019-10-07 kl  23 01 29" src="https://user-images.githubusercontent.com/756582/66348341-9ce19700-e956-11e9-97f6-1e4000dc7255.png">

**Comment by ttillberg** [comment]
I think that's a left-over from #22 - Got unnoticed since I don't have "notices" turned on. 

I guess this should fix it → https://github.com/ttillberg/acf-vimeo-pro-data/pull/27

**Comment by intelligence** [comment]
Yup, it's gone, thanks!
