### ISSUE TITLE
ACF Blocks not saving data?

### ISSUE THREAD

**Issue by dev-ofty** [ttillberg/acf-vimeo-pro-data#29]
Hello,

On a project we are currently using Gutenberg editor for the blog posts. In order to view video(s) in the content we are registering a custom block using ACF Blocks:
https://www.advancedcustomfields.com/resources/blocks/

The problem is that the data seems not to be saved after we hit the "update post". In the frontend nothing is shown, on the backend, it shows the video if we don't "hard refresh" the page.

I made a little video:
https://streamable.com/oa2vuq

Do you know why? The console doesn't error anything and no PHP error as well…

**Comment by ttillberg** [comment]
I'm sorry i'm not a user of ACF blocks so it's hard say what's going wrong here. But telling from your video it seems like it's rendering some boilerplate template. Is there some code required to configure the block perhaps ?

**Comment by dev-ofty** [comment]
No worries, I understand. 

To render the block you must use a custom template, inside that custom template we can use any normal ACF code. So I tried for instance: `$video = get_field('vimeo_video');` but the $video return everytime `NULL` as a result. That same template is used in the frontend and backend. 

It's like data is not stored after a save post creating the block. To answer, the only code that is required is the normal ACF code to get field value. At least according to the docs from ACF.

**Comment by kush1960** [comment]
Just ran in to this issue as well. Watching this issue.

**Comment by kush1960** [comment]
Fixed here https://github.com/ttillberg/acf-vimeo-pro-data/pull/31

**Comment by dev-ofty** [comment]
@kush1960 Thanks Kush, I didn't use that at the end but if it's fixed, will close this issue! I'm glad!
