### ISSUE TITLE
Sprite Support for Thumb Preview Srubber

### ISSUE THREAD

**Issue by StefanEndress** [ttillberg/acf-vimeo-pro-data#5]
This feature is more of a frontend feature, but vimeo does not provide sprites in their api. One approach could be ffmpeg integration and use the sd version serverside to generate these sprites.

*Original vimeo sprite*
https://i.vimeocdn.com/1502525522-0x4fd8bca5597706787bdaa335478fb3ffc8547e4f/sprite/229050224/120?q=48&h=126&ver=1&w=224&n=4

# Screenshot Scrubber Thumb
![image](https://user-images.githubusercontent.com/5189598/29238877-5e34b91c-7f3e-11e7-9872-d609422ad346.png)

**Comment by ttillberg** [comment]
@StefanEndress that would be useful indeed but I would rather do that as separate plugin or service. Mainly because it would require to install and configure ffmpeg.
